<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SimpleRobotController</AssemblyName>
    <ApplicationIcon>..\Simple Robot Controller Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HidSharp" Version="2.6.4" />
    <PackageReference Include="Makaretu.Dns.Multicast" Version="0.27.0" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260602" />
    <PackageReference Include="ZXing.Net" Version="0.16.9" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260602" Condition="$([MSBuild]::IsOSPlatform(Windows))" />
    <PackageReference Include="OpenCvSharp4.runtime.ubuntu.22.04-x64" Version="4.13.0.20260602" Condition="$([MSBuild]::IsOSPlatform(Linux))" />
    <PackageReference Include="System.IO.Ports" Version="9.0.0" />
  </ItemGroup>

</Project>
